# Generated by Django 5.2.16 on 2026-08-05 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
